### ISSUE TITLE
Enable import from webpack

### ISSUE THREAD

**Issue by ghost** [franciscop/pagex#4]
I managed to do this with just this line
```js
module.exports = pagex;
```

**Comment by franciscop** [comment]
Nowadays I prefer to do something I learned from React and use in my plain-js files: use component-based architecture. Instead of checking whether the current page is a specific page, do everything around an element. Example in `/article/edit/24534`:

```js
// Before
pagex('/article/edit/:id', id => { ... });

// Now:
const editor = document.querySelector('.editor');
if (editor) {
  const id = editor.id;
   ...
}
```

It is a few more characters, but in exchange it is a lot better in many situations. This is similar to browser sniffing (what page you are at) vs feature detection (what you can/should do). I will retrofit what you suggest though.

**Comment by franciscop** [comment]
Note: just bumped it to the 2.3
