### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by dave-irvine** [franciscop/pagex#5]
Hi!

Without transpiling this library doesn't work in IE11 due to arrow functions. Could you either add a transpile build step, or rework the arrow functions?

**Comment by franciscop** [comment]
Does this work?

```js
import pagex from 'pagex/pagex.min.js';
```

Or the equivalent if you are using a CDN. I didn't plan to support IE11/non-arrow-functions, but since the transpiled/minified script is here it might just work :)

**Comment by dave-irvine** [comment]
Unfortunately there are still arrow functions in the minified script.

**Comment by franciscop** [comment]
Oh yeah, sorry but as explained I stopped supporting ES5 a while ago. I thought the minified script might support IE11, but you are right it doesn't since it uses ES6+.

I don't support IE personally anymore, but you can do that on your side. Many modern tools allow for that, and please feel free to open an issue if you have an issue with the tool you use and I might be able to help.
